# Generated by Django 3.2.4 on 2021-06-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210629_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image1',
        ),
    ]
