# Generated by Django 3.2.4 on 2021-07-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddress_userpropic'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
