# Generated by Django 3.2.4 on 2021-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
